development:
  facebook_key: "YOUR_KEY"
  facebook_secret: "YOUR_SECRET"

  twitter_key: "mjD6tqj1iqYfHQBPu2JkOr767"
  twitter_secret: "bneIcjiz5bg6hrcu04e6mPeJfjjfUCrVwrzXXra4yXrmGBItyW"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"

production:
  facebook_key: "YOUR_KEY"
  facebook_secret: "YOUR_SECRET"

  twitter_key: "mjD6tqj1iqYfHQBPu2JkOr767"
  twitter_secret: "bneIcjiz5bg6hrcu04e6mPeJfjjfUCrVwrzXXra4yXrmGBItyW"

  github_key: "YOUR_KEY"
  github_secret: "YOUR_SECRET"

  linkedin_key: "YOUR_KEY"
  linkedin_secret: "YOUR_SECRET"

  google_key: "YOUR_KEY"
  google_secret: "YOUR_SECRET"
